import '~/styles/globals.css';
import '@mantine/core/styles.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
import { ClerkProvider } from '@clerk/nextjs';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { GeistSans } from 'geist/font/sans';
import { plPL } from '@clerk/localizations';

import { TRPCReactProvider } from '~/trpc/react';
import { Header } from '~/app/_components/Header';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider localization={plPL}>
      <html lang="en">
        <head suppressHydrationWarning>
          <ColorSchemeScript />
        </head>
        <body className={GeistSans.className}>
          <TRPCReactProvider>
            <MantineProvider>
              <Header />
              {children}
            </MantineProvider>
          </TRPCReactProvider>
          <SpeedInsights />
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
